<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>

    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <InvariantGlobalization>false</InvariantGlobalization>

    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>HDRReset</AssemblyName>
    <RootNamespace>HDRReset</RootNamespace>

    <EnableDefaultApplicationDefinition>true</EnableDefaultApplicationDefinition>
    <ApplicationManifest></ApplicationManifest>
  </PropertyGroup>

</Project>